# Generated by Django 3.0.3 on 2020-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pole123',
            field=models.TextField(default=''),
        ),
    ]
