# Generated by Django 3.0.3 on 2020-04-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueUser',
        ),
    ]
