# Generated by Django 3.0.3 on 2020-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author_pole123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
